bin: uniform the shell format
Signed-off-by: Philip Li <philip.li@intel.com>

diff --git a/bin/post-run b/bin/post-run
--- a/bin/post-run
+++ b/bin/post-run
@@ -23,7 +23,7 @@ any_pid_alive()
 		while read -r pid || [ -n "$pid" ]; do
 			[ -n "$pid" ] || continue
 			test -d "/proc/$pid" && return
-		done < "$pidfile"
+		done <"$pidfile"
 		return 1
 	fi
 }
@@ -35,8 +35,7 @@ wait_for_bg_procs()
 
 	echo wait for background processes: "$(cat "$pidfile" "$TMP/.name-wait-bg-procs")"
 
-	for i in $(seq 15)
-	do
+	for i in $(seq 15); do
 		sleep $i
 		any_pid_alive $pidfile && continue
 		return $i
@@ -48,7 +47,7 @@ wait_for_bg_procs()
 	else
 		ps axho pid | grep -Fxf $pidfile | xargs ps u
 		ps faux
-	fi > $TMP_RESULT_ROOT/bg-procs-debug
+	fi >$TMP_RESULT_ROOT/bg-procs-debug
 
 	return $i
 }
@@ -60,8 +59,7 @@ kill_bg_procs()
 	local pids
 	local pid
 
-	for pidfile in "$TMP"/pid-bg-proc-*
-	do
+	for pidfile in "$TMP"/pid-bg-proc-*; do
 		[ -s "$pidfile" ] || continue
 
 		if [ -s "$wait_pidfile" ]; then
@@ -72,12 +70,11 @@ kill_bg_procs()
 
 		[ -n "$pids" ] || continue
 
-		for pid in $pids
-		do
+		for pid in $pids; do
 			[ -d /proc/$pid ] || continue
 			explain_kill $pid
 			/bin/kill $signal $pid ||
-			echo "failed to kill background process	${pidfile##*/pid-bg-proc--}" >&2
+				echo "failed to kill background process	${pidfile##*/pid-bg-proc--}" >&2
 		done
 	done
 }
@@ -125,8 +122,7 @@ wait_for_pipe()
 	# will be missing.
 	[ -e $TMP/.pid-pipes ] || return
 
-	for i in $(seq 5)
-	do
+	for i in $(seq 5); do
 		sleep $i
 		if has_advance_pgrep; then
 			pgrep --pidfile $TMP/.pid-pipes 'tee|cat|gzip' >/dev/null && continue
@@ -136,12 +132,10 @@ wait_for_pipe()
 		break
 	done
 
-	for i in $(seq 5)
-	do
+	for i in $(seq 5); do
 		sleep $i
 
-		for result in ${tmp_results}
-		do
+		for result in ${tmp_results}; do
 			[ "${result%.gz}" != "$result" ] || continue
 			[ -s "$result" ] && continue
 
@@ -156,10 +150,10 @@ wait_for_pipe()
 
 	# Throw out stderr when monitors did not start due to waiting on activate-monitor
 	has_cmd pgrep &&
-	pgrep -f "$LKP_SRC/bin/event/wait activate-monitor" >/dev/null &&
+		pgrep -f "$LKP_SRC/bin/event/wait activate-monitor" >/dev/null &&
 		echo "some monitors are blocked by activate-monitor" >&2
 
-	ps faux 2>/dev/null > $RESULT_ROOT/pipe-debug || ps > $RESULT_ROOT/pipe-debug
+	ps faux 2>/dev/null >$RESULT_ROOT/pipe-debug || ps >$RESULT_ROOT/pipe-debug
 	ls -l $TMP_RESULT_ROOT
 	return 1
 }
@@ -183,12 +177,11 @@ copy_time_files()
 {
 	local ret_copy_time_files=0
 
-	for time_file in "$TMP"/*.time
-	do
+	for time_file in "$TMP"/*.time; do
 		[ -e "$time_file" ] || return
 
 		if upload_files $time_file; then
-			cat $time_file >> $TMP/time
+			cat $time_file >>$TMP/time
 		else
 			ret_copy_time_files=1
 		fi
@@ -199,7 +192,7 @@ copy_time_files()
 	return $ret_copy_time_files
 }
 
-copy_time_files || ps faux --cols 1000 2>/dev/null > $RESULT_ROOT/time-debug || ps > $RESULT_ROOT/time-debug
+copy_time_files || ps faux --cols 1000 2>/dev/null >$RESULT_ROOT/time-debug || ps >$RESULT_ROOT/time-debug
 
 copy_results
 
@@ -214,12 +207,11 @@ kmemleak_is_enabled && {
 }
 
 # the busybox reduced dmesg/truncate will refuse to run and it's not a big deal
-dmesg --facility user --human --decode --color=always > $TMP/umesg 2>/dev/null
+dmesg --facility user --human --decode --color=always >$TMP/umesg 2>/dev/null
 truncate --no-create --size='<10M' $TMP/output $TMP/stdout $TMP/stderr $TMP/umesg 2>/dev/null
 
 files=""
-for file in $TMP/boot-time $TMP/stdout $TMP/stderr $TMP/output $TMP/umesg $TMP/env.yaml $TMP/program_list $TMP/OOM $TMP/soft_timeout
-do
+for file in $TMP/boot-time $TMP/stdout $TMP/stderr $TMP/output $TMP/umesg $TMP/env.yaml $TMP/program_list $TMP/OOM $TMP/soft_timeout; do
 	[ -f $file ] && files="$files $file"
 done
 
@@ -244,7 +236,7 @@ upload_qemu_results()
 	}
 
 	upload_files -t host_result /tmp/host_rt/*
-	upload_files $guest_rt/*  # override the origin results
+	upload_files $guest_rt/* # override the origin results
 }
 
 need_run_on_vmm && upload_qemu_results
diff --git a/bin/run-stats b/bin/run-stats
--- a/bin/run-stats
+++ b/bin/run-stats
@@ -12,7 +12,7 @@ check_incomplete_run()
 	[[ -s $file ]] && return
 	[[ -f "$LKP_SRC/programs/$program/run" ]] || return
 
-	echo -e "# missing $program $file\nis_incomplete_run: 1" >> "$RESULT_ROOT/last_state"
+	echo -e "# missing $program $file\nis_incomplete_run: 1" >>"$RESULT_ROOT/last_state"
 }
 
 check_soft_timeout()
@@ -21,7 +21,7 @@ check_soft_timeout()
 	[[ -f $file ]] || return
 
 	grep -xq "soft_timeout: 1" "$RESULT_ROOT/last_state" ||
-	echo -e "soft_timeout: 1" >> "$RESULT_ROOT/last_state"
+		echo -e "soft_timeout: 1" >>"$RESULT_ROOT/last_state"
 }
 
 check_die()
@@ -130,7 +130,7 @@ check_empty_json()
 			return 1
 		else
 			log_warn "$stats_group: no json file generated" "$RESULT_ROOT"
-			echo -e "# no json file for $stats_group\nis_incomplete_run: 1" >> $RESULT_ROOT/last_state
+			echo -e "# no json file for $stats_group\nis_incomplete_run: 1" >>$RESULT_ROOT/last_state
 			return 1
 		fi
 	fi
@@ -138,8 +138,8 @@ check_empty_json()
 
 generate_log_from_serial()
 {
-	[[ -f $dmesg_log.xz ]] && xzcat "$dmesg_log".xz > "$dmesg_log"
-	[[ -f $kmsg_log.xz ]] && xzcat "$kmsg_log".xz > "$kmsg_log"
+	[[ -f $dmesg_log.xz ]] && xzcat "$dmesg_log".xz >"$dmesg_log"
+	[[ -f $kmsg_log.xz ]] && xzcat "$kmsg_log".xz >"$kmsg_log"
 
 	# remove [xxx][xxx] at the beginning of each line
 	# vi $RESULT_ROOT/dmesg.xz
@@ -150,9 +150,9 @@ generate_log_from_serial()
 	# [    0.000000][    T0] BIOS-provided physical RAM map:
 	# [    0.000000][    T0] BIOS-e820: [mem 0x0000000000000100-0x000000000009ebff] usable
 	if [[ -f $dmesg_log ]]; then
-		perl -pe 's/^(\[.*?\])* *//g' < "$dmesg_log" > "$log"
+		perl -pe 's/^(\[.*?\])* *//g' <"$dmesg_log" >"$log"
 	elif [[ -f $kmsg_log ]]; then
-		perl -pe 's/^(\[.*?\])* *//g' < "$kmsg_log" > "$log"
+		perl -pe 's/^(\[.*?\])* *//g' <"$kmsg_log" >"$log"
 	fi
 }
 
@@ -178,7 +178,10 @@ dump_stat()
 	local file=$2
 	local stat_file=$3
 
-	$LKP_SRC/sbin/dump-stat $stats_group $stat_file < $file || { log_error "failed to dump-stat $program" "errno: $?\nfile: $file"; exit 1; }
+	$LKP_SRC/sbin/dump-stat $stats_group $stat_file <$file || {
+		log_error "failed to dump-stat $program" "errno: $?\nfile: $file"
+		exit 1
+	}
 	rm $file
 }
 
@@ -210,24 +213,24 @@ LKP_SRC_ETC=$(lkp_src)/etc
 
 if [ -e $log.gz ]; then
 	[ -s $log.gz ] || exit 0
-	zcat $log.gz > $log
+	zcat $log.gz >$log
 elif [ -e $log.xz ]; then
 	[ -s $log.xz ] || exit 0
-	xzcat $log.xz > $log
+	xzcat $log.xz >$log
 fi
 
 kmsg_log=$RESULT_ROOT/kmsg
 
 # extract kmsg for kmsg related stats
 if [[ $log =~ ^"$RESULT_ROOT"/(boot-memory|boot-time|dmesg)$ ]]; then
-	[ -f $kmsg_log.xz ] && xzcat $kmsg_log.xz > $kmsg_log
+	[ -f $kmsg_log.xz ] && xzcat $kmsg_log.xz >$kmsg_log
 fi
 
 dmesg_log=$RESULT_ROOT/dmesg
 
 # extract dmesg for dmesg related stats
 if [[ $log =~ ^"$RESULT_ROOT"/kmsg$ ]]; then
-	[ -f $dmesg_log.xz ] && xzcat $dmesg_log.xz > $dmesg_log
+	[ -f $dmesg_log.xz ] && xzcat $dmesg_log.xz >$dmesg_log
 fi
 
 testcase=$(get_testcase)
@@ -248,26 +251,31 @@ check_env_issue || exit 1
 tmpfile=$(mktemp --tmpdir=/tmp lkp-stats.XXXXXXXX)
 if [[ -f "$log" ]]; then
 	# shellcheck disable=SC2094
-	"$program_path" "$log" < "$log" > "$tmpfile" || { log_error "failed to stat $program" "$program_path $log < $log\nerrno: $?\ntmpfile: $tmpfile"; is_bad_rt_candidate && exit 1; }
+	"$program_path" "$log" <"$log" >"$tmpfile" || {
+		log_error "failed to stat $program" "$program_path $log < $log\nerrno: $?\ntmpfile: $tmpfile"
+		is_bad_rt_candidate && exit 1
+	}
 else
-	"$program_path" < /dev/null > "$tmpfile" || { log_error "failed to stat $program" "$program_path < /dev/null\nerrno: $?\ntmpfile: $tmpfile"; is_bad_rt_candidate && exit 1; }
+	"$program_path" </dev/null >"$tmpfile" || {
+		log_error "failed to stat $program" "$program_path < /dev/null\nerrno: $?\ntmpfile: $tmpfile"
+		is_bad_rt_candidate && exit 1
+	}
 fi
 
 grep -q "^$program\." <(cat $LKP_SRC_ETC/failure $LKP_SRC_ETC/pass) ||
-check_incomplete_run $tmpfile
+	check_incomplete_run $tmpfile
 
 warn_empty_stats
 
 # cleanup program raw data
 [[ $is_empty_stats != 1 && $lite_mode == 1 ]] && {
-    rm -f $RESULT_ROOT/$program
-    rm -f $RESULT_ROOT/$program.xz
-    rm -f $RESULT_ROOT/$program.gz
+	rm -f $RESULT_ROOT/$program
+	rm -f $RESULT_ROOT/$program.xz
+	rm -f $RESULT_ROOT/$program.gz
 }
 
 if [[ $program = 'ftrace' ]]; then
-	for file in "$RESULT_ROOT/$program".*.yaml
-	do
+	for file in "$RESULT_ROOT/$program".*.yaml; do
 		stats_group=$(basename $file .yaml)
 		dump_stat $stats_group $file $stat_file
 	done
