programs: uniform the shell format
Signed-off-by: Philip Li <philip.li@intel.com>

diff --git a/programs/autonuma-benchmark/run b/programs/autonuma-benchmark/run
--- a/programs/autonuma-benchmark/run
+++ b/programs/autonuma-benchmark/run
@@ -18,33 +18,32 @@ ln -sf /usr/bin/gnuplot-qt /usr/bin/gnuplot
 # If test is not specified, will test all available tests.
 : "${test:=all}"
 case "$test" in
-	"all")
-		option="-A"
-		;;
-	"numa02_SMT")
-		option="-s"
-		;;
-	"numa01_THREAD_ALLOC")
-		option="-t"
-		;;
-	"numa02SMT_numa01THREAD_ALLOC")
-		option="-s -t"
-		;;
-	"_HARD_BIND")
-		option="-b"
-		;;
-	"_INVERSE_BIND")
-		option="-i"
-		;;
-	"minimal_thread_per_numa")
-		option="-m"
-		;;
-	*)
-		echo "Invalid test parameter." && exit 1
-		;;
+"all")
+	option="-A"
+	;;
+"numa02_SMT")
+	option="-s"
+	;;
+"numa01_THREAD_ALLOC")
+	option="-t"
+	;;
+"numa02SMT_numa01THREAD_ALLOC")
+	option="-s -t"
+	;;
+"_HARD_BIND")
+	option="-b"
+	;;
+"_INVERSE_BIND")
+	option="-i"
+	;;
+"minimal_thread_per_numa")
+	option="-m"
+	;;
+*)
+	echo "Invalid test parameter." && exit 1
+	;;
 esac
 
-for i in $(seq $iterations)
-do
+for i in $(seq $iterations); do
 	/bin/bash start_bench.sh $option 2>&1 || die "Autonuma run failed, check result log"
 done
diff --git a/programs/dd/run b/programs/dd/run
--- a/programs/dd/run
+++ b/programs/dd/run
@@ -5,13 +5,16 @@
 
 ## Copy a file, converting and formatting according to the operands.
 
-[[ -n "$mount_points" ]] || { echo "empty mount_points, disk failed?" >&2; exit; }
+[[ -n "$mount_points" ]] || {
+	echo "empty mount_points, disk failed?" >&2
+	exit
+}
 
 . $LKP_SRC/lib/reproduce-log.sh
 
 get_time_ms()
 {
-	echo $(($(date +%s%N)/1000000))
+	echo $(($(date +%s%N) / 1000000))
 }
 
 : "${runtime:=600}"
@@ -21,10 +24,8 @@ t=$(get_time_ms)
 
 files=
 pid=
-for i in $(seq ${nr_threads:-1})
-do
-	for mnt in $mount_points
-	do
+for i in $(seq ${nr_threads:-1}); do
+	for mnt in $mount_points; do
 		file=$mnt/zero-$i
 		files="$files $file "
 		rm -f $file
@@ -35,7 +36,7 @@ do
 done
 
 ps aux | grep dd
-echo $pid > $TMP/pid-dd
+echo $pid >$TMP/pid-dd
 
 tt=$(get_time_ms)
 startup_time=$((tt - t))
@@ -53,8 +54,8 @@ tt=$(get_time_ms)
 echo "kill_time_ms: $((tt - t))"
 
 chown lkp.lkp $TMP/pid-dd
-mv $TMP/pid-dd  $RESULT_ROOT/pid
-ls -li $files > $RESULT_ROOT/ls-files
+mv $TMP/pid-dd $RESULT_ROOT/pid
+ls -li $files >$RESULT_ROOT/ls-files
 truncate --size=0 $files
 rm -f $files
 
diff --git a/programs/kbuild/run b/programs/kbuild/run
--- a/programs/kbuild/run
+++ b/programs/kbuild/run
@@ -27,7 +27,12 @@ run_kbuild()
 		log_cmd scripts/config --file .config --enable CONFIG_TRIM_UNUSED_KSYMS
 
 		echo "start time: $(date +%s.%N)"
-		{ TIMEFORMAT=$'\nreal: %Rs\nuser: %Us\nsys: %Ss'; time { make -j $parallel $target > /dev/null; }; } 2>&1 || die "make -j $parallel $target failed"
+		{
+			TIMEFORMAT=$'\nreal: %Rs\nuser: %Us\nsys: %Ss'
+			time {
+				make -j $parallel $target >/dev/null
+			}
+		} 2>&1 || die "make -j $parallel $target failed"
 		echo "end time: $(date +%s.%N)"
 		iterations=$((iterations + 1))
 		now=$(date +%s)
@@ -56,9 +61,9 @@ for wdir in $kbuild_work_dirs; do
 	(
 		iwdir="$wdir/$instance_id"
 		log_eval cd "$iwdir"
-		run_kbuild > "$kbuild_tmp_dir/kbuild.$i"
+		run_kbuild >"$kbuild_tmp_dir/kbuild.$i"
 	) &
-	i=$((i+1))
+	i=$((i + 1))
 done
 
 wait
diff --git a/programs/lmbench3/run b/programs/lmbench3/run
--- a/programs/lmbench3/run
+++ b/programs/lmbench3/run
@@ -180,12 +180,13 @@ run_lmbench3_development()
 show_result()
 {
 	local LMBENCH_RESULT_PATH="$(find results/ -maxdepth 2 -name "${testbox}.0")"
-	cat $LMBENCH_RESULT_PATH|| die "no test result found"
+	cat $LMBENCH_RESULT_PATH || die "no test result found"
 }
 
-plot() {
-hostname="$1"
-gnuplot <<EOF
+plot()
+{
+	hostname="$1"
+	gnuplot <<EOF
 set terminal png medium size 1920,1080
 set output "lmbench_result.png"
 set title "Memory Latency Benchmark (Size=${size} Stride=${stride})"
@@ -203,7 +204,7 @@ EOF
 }
 
 if [[ "${standalone}" != "1" ]]; then
-	test_memory_size=$((test_memory_size/1024/1024))
+	test_memory_size=$((test_memory_size / 1024 / 1024))
 
 	# The bigger test memory range, the more accurate the results, but larger sizes
 	# take somewhat longer to run the benchmark.
@@ -212,7 +213,6 @@ if [[ "${standalone}" != "1" ]]; then
 	[[ "$test_memory_size" -gt 10240 ]] && test_memory_size=10240
 
 fi
-
 
 cd_benchmark
 
@@ -225,36 +225,36 @@ if [[ "${standalone}" != "1" ]]; then
 	[[ -n "$os" ]] && rm -rf $BENCHMARK_ROOT/lmbench3/results/$os/
 
 	case "$mode" in
-		'all') run_lmbench3_all ;;
-		'hardware') run_lmbench3_hardware ;;
-		'os') run_lmbench3_os ;;
-		'development') run_lmbench3_development ;;
-		*) echo "invalid running mode:$mode in lmbench3" && exit 1
-		esac
+	'all') run_lmbench3_all ;;
+	'hardware') run_lmbench3_hardware ;;
+	'os') run_lmbench3_os ;;
+	'development') run_lmbench3_development ;;
+	*) echo "invalid running mode:$mode in lmbench3" && exit 1 ;;
+	esac
 
 	show_result
 
 else
 
 	case "$test" in
-		'lat_mem_rd')
-			TEST_BIN_PATH="$(find bin/ -maxdepth 2 -name lat_mem_rd)"
-			echo "Running memory load latency..."
-			log_cmd ./${TEST_BIN_PATH} -P ${nr_parallelism} ${size} ${stride} > $TMP_RESULT_ROOT/lmbench3 2>&1
+	'lat_mem_rd')
+		TEST_BIN_PATH="$(find bin/ -maxdepth 2 -name lat_mem_rd)"
+		echo "Running memory load latency..."
+		log_cmd ./${TEST_BIN_PATH} -P ${nr_parallelism} ${size} ${stride} >$TMP_RESULT_ROOT/lmbench3 2>&1
 
-			LMBENCH_RESULT="$TMP_RESULT_ROOT/extract-lmbench3"
-			sed '1,2d' $TMP_RESULT_ROOT/lmbench3 > ${LMBENCH_RESULT}
+		LMBENCH_RESULT="$TMP_RESULT_ROOT/extract-lmbench3"
+		sed '1,2d' $TMP_RESULT_ROOT/lmbench3 >${LMBENCH_RESULT}
 
-			plot ${testbox}
+		plot ${testbox}
 
-			rm ${LMBENCH_RESULT}
-			mv lmbench_result.png $TMP_RESULT_ROOT/lmbench_result.png
+		rm ${LMBENCH_RESULT}
+		mv lmbench_result.png $TMP_RESULT_ROOT/lmbench_result.png
 		;;
-		'bw_mem')
-			TEST_BIN_PATH="$(find bin/ -maxdepth 2 -name bw_mem)"
-			echo "Running memory bandwitch test..."
-			log_cmd ./${TEST_BIN_PATH} -P ${nr_parallelism} ${size} ${op} > $TMP_RESULT_ROOT/lmbench3 2>&1
+	'bw_mem')
+		TEST_BIN_PATH="$(find bin/ -maxdepth 2 -name bw_mem)"
+		echo "Running memory bandwitch test..."
+		log_cmd ./${TEST_BIN_PATH} -P ${nr_parallelism} ${size} ${op} >$TMP_RESULT_ROOT/lmbench3 2>&1
 		;;
-		*) echo "invalid test:$test in lmbench3" && exit 1
+	*) echo "invalid test:$test in lmbench3" && exit 1 ;;
 	esac
 fi
diff --git a/programs/ltp/run b/programs/ltp/run
--- a/programs/ltp/run
+++ b/programs/ltp/run
@@ -25,11 +25,11 @@ log_cmd export LTP_RUNTIME_MUL=2
 log_cmd export LTPROOT="$(get_benchmark_path)" # used by kirk
 
 if [[ -f "$BENCHMARK_ROOT/ltp/runtest/$test" ]]; then
-    log_cmd kirk -f $test $big_dev_opt $tmpdir_opt
+	log_cmd kirk -f $test $big_dev_opt $tmpdir_opt
 elif [[ -f "$BENCHMARK_ROOT/ltp/runtest/temp_single_test" ]]; then
-    log_cmd kirk -f temp_single_test $big_dev_opt $tmpdir_opt
+	log_cmd kirk -f temp_single_test $big_dev_opt $tmpdir_opt
 else
-    die "ltp test cmdfile is not found"
+	die "ltp test cmdfile is not found"
 fi
 
 cleanup_ltp $test
@@ -38,18 +38,18 @@ kirk_latest="/tmp/kirk.$(whoami)/latest"
 kirk_results_json="$kirk_latest/results.json"
 
 if [[ -d "$kirk_latest" ]]; then
-    if [[ -f "$kirk_results_json" ]]; then
-        echo "LTP test details"
-        echo "----------------"
+	if [[ -f "$kirk_results_json" ]]; then
+		echo "LTP test details"
+		echo "----------------"
 
-        if ! jq -r '.results[]? as $r | ($r.test.log? // "" | split("\n") | map(select(test("TFAIL|TBROK|TWARN|TCONF"))) | unique) as $details | select((($r.status // "") != "pass") or (($details | length) > 0)) | if ($details | length) > 0 then $details[] | "\($r.test_fqn): \(.)" else "\($r.test_fqn): \($r.status)" end' "$kirk_results_json"; then
-            echo "Failed to parse $kirk_results_json by jq" 1>&2
-        fi
-    fi
+		if ! jq -r '.results[]? as $r | ($r.test.log? // "" | split("\n") | map(select(test("TFAIL|TBROK|TWARN|TCONF"))) | unique) as $details | select((($r.status // "") != "pass") or (($details | length) > 0)) | if ($details | length) > 0 then $details[] | "\($r.test_fqn): \(.)" else "\($r.test_fqn): \($r.status)" end' "$kirk_results_json"; then
+			echo "Failed to parse $kirk_results_json by jq" 1>&2
+		fi
+	fi
 
-    upload_files -t results "$kirk_latest"/* 2>&1
+	upload_files -t results "$kirk_latest"/* 2>&1
 else
-    echo "$kirk_latest is not found"
+	echo "$kirk_latest is not found"
 fi
 
 exit 0
diff --git a/programs/nvdimm/setup b/programs/nvdimm/setup
--- a/programs/nvdimm/setup
+++ b/programs/nvdimm/setup
@@ -19,18 +19,18 @@ keep_quiet()
 __probe_devs()
 {
 	case "$mode" in
-		raw|fsdax)
-			# shellcheck disable=SC2010
-			rdevs=$(ls /dev/pmem* | grep '/dev/pmem[0-9]\+$')
-			;;
-		dax)
-			rdevs=$(ls /dev/dax*)
-			ignore_parts=1
-			;;
-		*)
-			echo "Invalid nvdimm mode: $mode!" >&2
-			exit 1
-			;;
+	raw | fsdax)
+		# shellcheck disable=SC2010
+		rdevs=$(ls /dev/pmem* | grep '/dev/pmem[0-9]\+$')
+		;;
+	dax)
+		rdevs=$(ls /dev/dax*)
+		ignore_parts=1
+		;;
+	*)
+		echo "Invalid nvdimm mode: $mode!" >&2
+		exit 1
+		;;
 	esac
 	rnr_dev=$(echo $rdevs | wc -w)
 	: "${nr_dev:=$rnr_dev}"
@@ -143,7 +143,7 @@ else
 	probe_create_parts
 fi
 
-cat >> $TMP/env.yaml <<EOF
+cat >>$TMP/env.yaml <<EOF
 
 # setup/nvdimm
 nr_partitions: $nr_part
diff --git a/programs/packetdrill/run b/programs/packetdrill/run
--- a/programs/packetdrill/run
+++ b/programs/packetdrill/run
@@ -14,19 +14,19 @@ cd_benchmark $suite/gtests/net/packetdrill
 lsmod | grep -q tun || modprobe tun
 
 find . -name "*.pkt" ! -name "*diag-ipv6*" | sort |
-while read -r f; do
-	echo "Running $f ..."
-	ip tcp_metrics flush all > /dev/null 2>&1
-	# default tolerance_usecs is 4000 us, allow 10 times(4000 us) on LKP
-	opts=$(grep -q -- --tolerance_usecs $f >/dev/null 2>&1 || echo "--tolerance_usecs=40000")
-	log_cmd ./packetdrill $opts $f 2>&1
-	return_value=$?
-	if [[ $return_value -eq 0 ]]; then
-		echo "$f pass"
-	else
-		echo "$f failed"
-	fi
-done
+	while read -r f; do
+		echo "Running $f ..."
+		ip tcp_metrics flush all >/dev/null 2>&1
+		# default tolerance_usecs is 4000 us, allow 10 times(4000 us) on LKP
+		opts=$(grep -q -- --tolerance_usecs $f >/dev/null 2>&1 || echo "--tolerance_usecs=40000")
+		log_cmd ./packetdrill $opts $f 2>&1
+		return_value=$?
+		if [[ $return_value -eq 0 ]]; then
+			echo "$f pass"
+		else
+			echo "$f failed"
+		fi
+	done
 
 # Pass --tolerance_usecs=100000 to packetdrill command
 grep -q -- --tolerance_usecs ./run_all.py || sed -ri 's/(--send_omit_free)/\1 --tolerance_usecs=100000/g' ./run_all.py
