stats/wrapper: move all functions in the beginning
Signed-off-by: Philip Li <philip.li@intel.com>

diff --git a/stats/wrapper b/stats/wrapper
--- a/stats/wrapper
+++ b/stats/wrapper
@@ -5,32 +5,6 @@ source $LKP_SRC/lib/lkp_path.sh
 
 set -o pipefail
 
-program_dir=$(dirname $0)
-program=$1
-
-parser_path=$program_dir/$program
-[ -x $parser_path ] || parser_path=$LKP_SRC/programs/$program/parse
-
-stats_group=${2:-$1}
-log=$RESULT_ROOT/$stats_group
-
-LKP_SRC_ETC=$(lkp_src)/etc
-# exit processing the stats if the program is not in the program_list.
-# program_list is a file that records all the programs(setups, monitors, tests,
-# daemons) being executed during the test.
-# this is to solve the problem for cluster test jobs running on the server node
-# where no program's log file is generated for running server daemons but the
-# stats processing for the program running on client node will also be handled
-# on server node due to the current Job2sh algorithm.
-
-# default stats are not in the program_list
-grep -q "^$program\:" $LKP_SRC_ETC/default_stats.yaml
-if [ $? -ne 0 ]; then
-	[ -f $RESULT_ROOT/program_list ] && {
-		grep -q "$program" $RESULT_ROOT/program_list || exit 0
-	}
-fi
-
 check_incomplete_run()
 {
 	local file=$1
@@ -162,6 +136,78 @@ check_empty_json()
 	fi
 }
 
+generate_log_from_serial()
+{
+	[[ -f $dmesg_log.xz ]] && xzcat "$dmesg_log".xz > "$dmesg_log"
+	[[ -f $kmsg_log.xz ]] && xzcat "$kmsg_log".xz > "$kmsg_log"
+
+	# remove [xxx][xxx] at the beginning of each line
+	# vi $RESULT_ROOT/dmesg.xz
+	# [    0.000000][    T0] x86/fpu: Supporting XSAVE feature 0x004: 'AVX registers'
+	# [    0.000000][    T0] x86/fpu: xstate_offset[2]:  576, xstate_sizes[2]:  256
+	# [    0.000000][    T0] x86/fpu: Enabled xstate features 0x7, context size is 832 bytes, using 'standard' format.
+	# [    0.000000][    T0] signal: max sigframe size: 1776
+	# [    0.000000][    T0] BIOS-provided physical RAM map:
+	# [    0.000000][    T0] BIOS-e820: [mem 0x0000000000000100-0x000000000009ebff] usable
+	if [[ -f $dmesg_log ]]; then
+		perl -pe 's/^(\[.*?\])* *//g' < "$dmesg_log" > "$log"
+	elif [[ -f $kmsg_log ]]; then
+		perl -pe 's/^(\[.*?\])* *//g' < "$kmsg_log" > "$log"
+	fi
+}
+
+# When stats script returns failure, we need decide whether it is a bad rt
+# - job exists due to die, so that rt is bad. This is handled in check_die.
+# - job has soft_timeout or OOM or panic, which may lead to the incomplete/missing
+# output. The rt is not necessarily bad.
+# - job runs to the end without the serious states mentioned in above bullets, then
+# if any output is incomplete/missing, it is a bad rt.
+is_bad_rt_candidate()
+{
+	[[ -f $RESULT_ROOT/last_state ]] || return 0
+
+	# rli9 FIXME the logic can't handle panic situation now
+	grep -q -e "soft_timeout: 1" -e "OOM: 1" $RESULT_ROOT/last_state && return 1
+
+	return 0
+}
+
+dump_stat()
+{
+	local stats_group=$1
+	local file=$2
+	local stat_file=$3
+
+	$LKP_SRC/sbin/dump-stat $stats_group $stat_file < $file || { log_error "failed to dump-stat $program" "errno: $?\nfile: $file"; exit 1; }
+	rm $file
+}
+
+program_dir=$(dirname $0)
+program=$1
+
+parser_path=$program_dir/$program
+[ -x $parser_path ] || parser_path=$LKP_SRC/programs/$program/parse
+
+stats_group=${2:-$1}
+log=$RESULT_ROOT/$stats_group
+
+LKP_SRC_ETC=$(lkp_src)/etc
+# exit processing the stats if the program is not in the program_list.
+# program_list is a file that records all the programs(setups, monitors, tests,
+# daemons) being executed during the test.
+# this is to solve the problem for cluster test jobs running on the server node
+# where no program's log file is generated for running server daemons but the
+# stats processing for the program running on client node will also be handled
+# on server node due to the current Job2sh algorithm.
+
+# default stats are not in the program_list
+grep -q "^$program\:" $LKP_SRC_ETC/default_stats.yaml
+if [ $? -ne 0 ]; then
+	[ -f $RESULT_ROOT/program_list ] && {
+		grep -q "$program" $RESULT_ROOT/program_list || exit 0
+	}
+fi
+
 if [ -e $log.gz ]; then
 	[ -s $log.gz ] || exit 0
 	zcat $log.gz > $log
@@ -184,26 +230,6 @@ if [[ $log =~ ^"$RESULT_ROOT"/kmsg$ ]]; then
 	[ -f $dmesg_log.xz ] && xzcat $dmesg_log.xz > $dmesg_log
 fi
 
-generate_log_from_serial()
-{
-	[[ -f $dmesg_log.xz ]] && xzcat "$dmesg_log".xz > "$dmesg_log"
-	[[ -f $kmsg_log.xz ]] && xzcat "$kmsg_log".xz > "$kmsg_log"
-
-	# remove [xxx][xxx] at the beginning of each line
-	# vi $RESULT_ROOT/dmesg.xz
-	# [    0.000000][    T0] x86/fpu: Supporting XSAVE feature 0x004: 'AVX registers'
-	# [    0.000000][    T0] x86/fpu: xstate_offset[2]:  576, xstate_sizes[2]:  256
-	# [    0.000000][    T0] x86/fpu: Enabled xstate features 0x7, context size is 832 bytes, using 'standard' format.
-	# [    0.000000][    T0] signal: max sigframe size: 1776
-	# [    0.000000][    T0] BIOS-provided physical RAM map:
-	# [    0.000000][    T0] BIOS-e820: [mem 0x0000000000000100-0x000000000009ebff] usable
-	if [[ -f $dmesg_log ]]; then
-		perl -pe 's/^(\[.*?\])* *//g' < "$dmesg_log" > "$log"
-	elif [[ -f $kmsg_log ]]; then
-		perl -pe 's/^(\[.*?\])* *//g' < "$kmsg_log" > "$log"
-	fi
-}
-
 testcase=$(get_testcase)
 
 category=$(grep "^category" "$RESULT_ROOT"/job.yaml | awk '{print $2}')
@@ -219,22 +245,6 @@ check_binary_output
 check_die || exit 1
 check_env_issue || exit 1
 
-# When stats script returns failure, we need decide whether it is a bad rt
-# - job exists due to die, so that rt is bad. This is handled in check_die.
-# - job has soft_timeout or OOM or panic, which may lead to the incomplete/missing
-# output. The rt is not necessarily bad.
-# - job runs to the end without the serious states mentioned in above bullets, then
-# if any output is incomplete/missing, it is a bad rt.
-is_bad_rt_candidate()
-{
-	[[ -f $RESULT_ROOT/last_state ]] || return 0
-
-	# rli9 FIXME the logic can't handle panic situation now
-	grep -q -e "soft_timeout: 1" -e "OOM: 1" $RESULT_ROOT/last_state && return 1
-
-	return 0
-}
-
 tmpfile=$(mktemp --tmpdir=/tmp lkp-stats.XXXXXXXX)
 if [[ -f $log ]]; then
 	$parser_path $log < $log > $tmpfile || { log_error "failed to stat $program" "$parser_path $log < $log\nerrno: $?\ntmpfile: $tmpfile"; is_bad_rt_candidate && exit 1; }
@@ -246,16 +256,6 @@ grep -q "^$program\." <(cat $LKP_SRC_ETC/failure $LKP_SRC_ETC/pass) ||
 check_incomplete_run $tmpfile
 
 warn_empty_stats
-
-dump_stat()
-{
-	local stats_group=$1
-	local file=$2
-	local stat_file=$3
-
-	$LKP_SRC/sbin/dump-stat $stats_group $stat_file < $file || { log_error "failed to dump-stat $program" "errno: $?\nfile: $file"; exit 1; }
-	rm $file
-}
 
 # cleanup program raw data
 [[ $is_empty_stats != 1 && $lite_mode == 1 ]] && {
