stats/wrapper: switch to simple stderr for several warnings
Signed-off-by: Philip Li <philip.li@intel.com>

diff --git a/stats/wrapper b/stats/wrapper
--- a/stats/wrapper
+++ b/stats/wrapper
@@ -56,7 +56,7 @@ check_die()
 	[[ -f $RESULT_ROOT/last_state ]] || return 0
 
 	grep -q "exit_code.99: 1" $RESULT_ROOT/last_state && {
-		log_warn "job exited due to die" "$RESULT_ROOT"
+		echo "job exited due to die: $RESULT_ROOT" 1>&2
 		return 1
 	}
 
@@ -70,7 +70,7 @@ check_env_issue()
 	[[ -f $RESULT_ROOT/last_state ]] || return 0
 
 	grep -q "wget_initrd_fail: 1" $RESULT_ROOT/last_state && {
-		log_warn "job exited due to wget_initrd_fail" "$RESULT_ROOT"
+		echo "job exited due to wget_initrd_fail: $RESULT_ROOT" 1>&2
 		return 1
 	}
 
